### ISSUE TITLE
Enabling this extension causes an internal server error when updating groups through the UI.

### ISSUE THREAD

**Issue by jstp959** [espona/ckanext-restricted#11] opened 2019-06-04 14:16 UTC
Hello,

I am running CKAN 2.7, and in my .ini file I only specify the following plugins:
`ckan.plugins = stats text_view image_view recline_view scheming_datasets composite repeating restricted`

When I go to edit a group (/group/edit/myGroup), and then click the "Update Group" button, I get an internal server error with the following traceback:
![Capture](https://user-images.githubusercontent.com/10671807/58886170-71e9ec80-86b1-11e9-8abe-b9646f06a615.png)

That obj tuple represents a tag named "Opportunities", and the first element in the tuple is its ID. I'm not sure why a tag object would pass through the restricted_package_show function?

This only occurs when I have the restricted extension enabled, and removing it causes the issue to go away.

Any assistance would be greatly appreciated!

**Comment by espona** [comment] 2019-06-12 11:08
Unfortunately I cannot reproduce the error. Are you sure the extension is properly installed and configured? Does it work well for the resources and datasets?

**Comment by jstp959** [comment] 2019-06-21 19:25
Thanks for the response, it does work well for the resources and datasets for some reason, and it only happens for some groups. I've also discovered this happens when I view the dashboard

**Comment by MandanaMoshref** [comment] 2019-11-19 23:22
@jstp959 I had the same problem/error in loading the start page. It was resolved by rebuilding the Solr index.
Try this. I believe it solves your problem

**Closed as completed** 2020-05-13 17:18 UTC
